### PR TITLE
Refactor setup

### PR DESCRIPTION
**Pull request by Kaniee**

### CODE REVIEW

**Comment by krocheck** [comment]
The main thing standing out to me is in the lookup tables.  I'd much prefer the keys to be the hexes and values to be the human readable flavor.

**Comment by Kaniee** [comment]
Out of curiosity, what is your reasoning behind that?
My main reason behind that design was, that I'm using these lookup tables mainly to map/translate the human readable value to hex and not the other way around and with this design I can assure, that there is no option multiple times in that list.
But in the end that should also be true for the hexes.
I was refactoring that part multiple times and now I'm thinking that a solution I had earlier might have been the cleanest solution:
```javascript
const optionsArray = [
  { name: 'On', value: 0x02 },
  { name: 'Off', value: 0x03 }
]
```
The only reason I dropped that design was the repeating ` { name: ..., value: ...}` pattern.
What do you think about that?
The object array approach would allow extensions like comment or translations fields.

**Comment by krocheck** [comment]
@Kaniee the main reason is that the hex is a fixed value for what it represents but the human readable text can be subject to change.  e.g.
```javascript
exports.powerModeArray = {
    'On':            0x02,
    'Off (Standby)': 0x03
}
```
If for some reason `Off (Standby)` needed to be changed to `Off` or `Off (standby)` that change would break existing selections because of the key change where-as the hex hasn't changed.  I see where you're going with the array but if you mapped them like this instead they would directly translate to the choice dropdowns, which is acceptable and done in plenty of examples.
```javascript
const optionsArray = [
  { label: 'On', id: 0x02 },
  { label: 'Off', id: 0x03 }
]
```

**Comment by Kaniee** [comment]
@krocheck I fully agree with the with the issue on changing labels.
I remember now that this was the reason I moved to use the object array before I got annoyed by the repeating bits of code and went back to my original solution (and forgetting my initial reasoning behind the change 🤦‍♂️)

I'll go ahead and make that change. But I'm not sure yet on the key names. I'm planning the move the VISCA specific code into a npm package so it can be used for other projects as well (including other Companion modules). Therefor I don't want to design/name stuff specifically for Companion but nevertheless it's the main driver for that code.

**Pull request merged**
